import type { Metadata } from "next";
import { Do_Hyeon } from "next/font/google";
import "./globals.css";
import "./styles/style.css";
import { css } from "../../styled-system/css";
import { stack } from "../../styled-system/patterns/stack.mjs";

const inter = Do_Hyeon({ subsets: ["latin"], weight: "400", display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={stack({ gap: "6", padding: "4" })}>{children}</main>
      </body>
    </html>
  );
}
